INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Amelie', 'O''Reilly', '7358 Ziemann Track', 'Zechariahhaven', '16895', 'Willow.Waters47@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Erika', 'O''Kon', '45371 Jolie Ways', 'Madelineville', '49007-0173', 'Yvonne.Witting@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Mittie', 'Batz', '2591 Kuphal Branch', 'Elisabethchester', '68919-9729', 'Kenya.Bogan@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Nannie', 'Koelpin', '25655 Beryl Parkways', 'Schowalterville', '63142', 'Monique.Mitchell@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Oda', 'Sawayn', '38316 Mike Common', 'Lake Alek', '00490', 'Berneice_Barrows28@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Vesta', 'Toy', '138 Kadin Pine', 'New Emmanuelchester', '34125-4488', 'Lucinda.Strosin@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Moriah', 'Paucek', '958 Gerlach Freeway', 'Boscoville', '86172-0239', 'Karen.Jacobi14@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Sibyl', 'Kessler', '206 Jessica Rest', 'North Emma', '51989', 'Amelia.Kessler@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Chaim', 'Kovacek', '6296 Borer Mountain', 'Angelobury', '43170-1311', 'Kyler_Kerluke@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Luisa', 'Sipes', '7611 Eleonore Loaf', 'East Rowland', '77863', 'Loren_Wolf@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Clovis', 'Schmitt', '0706 Tromp Mount', 'South Maximillianshire', '14893', 'Dexter70@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('August', 'Zemlak', '06199 Manley Parkway', 'West Katrineshire', '63771-4593', 'Cyrus94@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Darrick', 'Nitzsche', '25309 Lucie Green', 'North Kayden', '25910', 'Dina.Hickle@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Therese', 'Krajcik', '43610 Aletha Plaza', 'Harberborough', '87028', 'Cleveland69@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Deja', 'Rutherford', '5954 Harris Mall', 'Port Elvis', '32413', 'Laurel.Howell20@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Johnson', 'Pfeffer', '406 Hyatt Cliff', 'Weberville', '44817', 'Coralie29@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Delaney', 'Kuhlman', '818 Larson Circle', 'West Royalmouth', '97830', 'Hal.Brown12@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Piper', 'Windler', '956 Alyce Parks', 'Lake Andymouth', '05626', 'Rod.Herzog56@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Jarrett', 'Sanford', '5250 Vidal Island', 'New Dorcas', '95741', 'Kaci.Schneider@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Crystel', 'Homenick', '75151 Ebert Manor', 'West Xander', '67717', 'Jayden43@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Bridget', 'Quigley', '329 Minnie Village', 'Ernestinaton', '52333', 'Maddison.Lind95@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Isidro', 'Hansen', '763 Leila Greens', 'Port Toney', '23376', 'Ava45@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Keira', 'Hintz', '459 Raynor Loaf', 'Nigelberg', '43591', 'Lavina.Witting@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Elvera', 'Oberbrunner', '842 Quitzon Stream', 'East Drake', '78165', 'Carli46@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Rocky', 'Metz', '209 Rowe Burg', 'Port Michaela', '86586', 'Lukas.Conroy@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Rhiannon', 'Cartwright', '0482 Yvette Streets', 'New Amiya', '22253', 'Emerald77@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Shany', 'Keeling', '001 Mohammad Run', 'New Nicholaston', '33009-1504', 'Duane_Lesch@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Lauren', 'Larkin', '681 Marvin Motorway', 'Port Thomasview', '49710-2903', 'Kris_Kiehn26@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Pearl', 'Lakin', '9572 Kayden Trace', 'Hudsonfort', '11073', 'Lionel.Fadel@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Erick', 'Welch', '9127 Hammes Drive', 'South Delfinaburgh', '49770', 'Leif_Smitham@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Oceane', 'Herman', '112 Wiza Rapids', 'New Cristina', '02729', 'Mark47@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Theresia', 'Wisozk', '07225 Yundt Lakes', 'Lake Elena', '42169', 'Vivian35@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Kaitlin', 'VonRueden', '921 Beahan Station', 'Natashafurt', '66974-6287', 'Claudie_Moen53@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Jazmyne', 'Kerluke', '987 Melisa Junction', 'Orvalchester', '34752-6648', 'Cayla_Jacobs83@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Larry', 'Hegmann', '8805 Hans Vista', 'Alvaville', '25565-4938', 'Aron.Crooks@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Al', 'Nitzsche', '43705 Avery Extension', 'East Chestertown', '21089', 'Valentina_Kozey@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Elian', 'Morar', '125 Tate Club', 'Elinorestad', '55136-9300', 'Bartholome53@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Ulises', 'Sipes', '50702 Zechariah Cove', 'West Eleanoreshire', '82673', 'Jacklyn0@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Kaylah', 'Satterfield', '407 Kemmer Ridges', 'East Elmiratown', '51484', 'Nathanael.Wintheiser@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Dwight', 'Wilderman', '6026 McDermott Landing', 'Welchshire', '65834', 'Camron_Haley33@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Brody', 'Doyle', '118 Domenic View', 'West Tiannaland', '31955-0892', 'Jeramy.Murphy@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Cornell', 'Hoppe', '863 Mavis Walks', 'Geovannitown', '69868-1705', 'Brady11@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Nigel', 'Hessel', '7116 Isabella Terrace', 'Hackettstad', '05297-5211', 'Zakary.Larson78@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Jennie', 'Schowalter', '763 Adrienne Light', 'Llewellynberg', '18595', 'Carolina_Klein89@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Jamal', 'Kris', '712 Zack Falls', 'Adaland', '34137-1753', 'Enrique.Marquardt@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Gust', 'Robel', '89665 Ignacio Forge', 'Jamaalside', '56804', 'Mable.Lesch@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Otilia', 'Maggio', '90642 Peter Cliff', 'New Rosemariemouth', '17047', 'Diamond17@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Leila', 'Walker', '234 Mariela Trail', 'Cormierview', '23653', 'Lesly.Cole55@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Gay', 'Lebsack', '5416 Kling Ramp', 'Margetown', '26463', 'Rick.DAmore2@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Maye', 'Rempel', '777 Kunze Cliffs', 'East Coltenburgh', '65627-9264', 'Ali.Lueilwitz63@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Willow', 'Murazik', '222 Marianna Stravenue', 'Lake Adrienne', '23676-7817', 'Brian_Murazik7@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Elda', 'Kuhn', '2709 Coty Heights', 'Elliotttown', '37505', 'Velma.Ullrich87@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Lelah', 'Abshire', '5774 D''angelo Crescent', 'West Natashafurt', '52518-9342', 'Lorenzo_Vandervort31@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Melba', 'White', '709 Herman Cliff', 'Gladysborough', '78159', 'Spencer.Cartwright@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Nikolas', 'Hoeger', '1240 Terrence Crest', 'Hegmannland', '22586', 'Bethany_Batz@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Easton', 'Paucek', '911 Ruecker Overpass', 'Lake Emmaleefort', '69889-9834', 'Florencio.Doyle98@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Carmella', 'Raynor', '951 Schowalter Extensions', 'New Gaetanobury', '29901-1914', 'Cheyenne30@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Joe', 'Harber', '95583 Pete Hill', 'West Abigayleville', '00757', 'Caitlyn19@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Rico', 'Ullrich', '5944 Antone Loaf', 'Port Mertie', '79150-9911', 'Imani72@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Bonnie', 'Ryan', '746 Raynor Inlet', 'Brakuston', '34328-3169', 'Rosemary69@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Josiane', 'Rau', '30513 Beahan Lodge', 'East Rodolfoshire', '09242', 'Katrina38@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Ben', 'Jerde', '37565 Huel Common', 'Brakusburgh', '46677-5084', 'Dixie.Mosciski84@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Kelly', 'Corkery', '1436 Daniel Cliff', 'East Terrellview', '44830-1502', 'Estefania_Upton24@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Brielle', 'DuBuque', '3271 Jacynthe Shoals', 'West Alanna', '54815-3139', 'Maybell_Anderson@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Boyd', 'White', '00796 Ernser Ridges', 'Fredrickshire', '63363', 'Rachael.Blick65@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Noel', 'Bruen', '991 Ebert Station', 'Myrlstad', '27927', 'Ewald89@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Santino', 'Jenkins', '418 Kacie Island', 'Eltonshire', '64101', 'Afton.Hickle96@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Dashawn', 'Kulas', '6364 Trantow Mission', 'Cummingstown', '37842', 'Sheila94@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Jannie', 'Volkman', '5069 McKenzie Square', 'New Danikaside', '20319-3422', 'Anya30@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Tomasa', 'Stamm', '651 Dillan Cliffs', 'Gunnerland', '24602', 'Meda_Towne@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Myrna', 'Hyatt', '96147 Bradtke Ville', 'Lake Ellis', '58061', 'Rey5@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Murray', 'Weissnat', '581 Gusikowski Crescent', 'North Imani', '03697', 'Geo31@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Josephine', 'West', '6879 Stark Springs', 'Lake Delfinafort', '33900-9601', 'Jackson_Maggio@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Keshawn', 'Bogisich', '78017 Dickinson Curve', 'Dominiquebury', '44698-7814', 'Athena.Funk@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Titus', 'Sawayn', '5229 Asa Spur', 'South Alaynaburgh', '37923-5403', 'Gunner_Jerde@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Constance', 'Rice', '7442 Crist Harbors', 'Grantmouth', '23265', 'Mossie_Willms@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Lucie', 'Toy', '379 Edward Cliffs', 'Mitchelltown', '52777', 'Keyshawn_Heidenreich@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Kristina', 'Schiller', '3342 Conner Isle', 'Hopeside', '79934', 'Christine82@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Gregorio', 'Botsford', '65174 Faustino Spring', 'North Salma', '90881', 'Eunice.Cole25@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Lou', 'Crooks', '7598 Lind Extension', 'New Helenaburgh', '23563-7301', 'Neil_Howe@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Bulah', 'Kohler', '029 Schuster Plains', 'Spencerborough', '49254-6989', 'Woodrow_Graham64@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Reagan', 'O''Conner', '32223 Ally Mill', 'Langhaven', '72670', 'Dewitt_Schamberger@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Elfrieda', 'O''Keefe', '2592 Cheyanne Stream', 'East Royal', '13962', 'Heath.Upton78@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Rosetta', 'Wisoky', '86896 Legros Ridges', 'Cummingshaven', '76694', 'Jeramie_Barton4@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Lola', 'McKenzie', '50991 Mose Turnpike', 'Ernserberg', '05725-4607', 'Jeanne.OConner@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Shyanne', 'Batz', '8857 Johathan Hill', 'Hankmouth', '04113', 'Elva35@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Nathen', 'Schowalter', '67061 Stracke Street', 'Othamouth', '25399', 'Domenico_Cole@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Ruth', 'Grant', '06583 Sadye Overpass', 'Hildaborough', '41409-7452', 'Laury22@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Arnold', 'Friesen', '4520 Upton Parkways', 'Huelborough', '40530-3029', 'Percival.Keeling13@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Corine', 'Dicki', '1163 Damien Expressway', 'Port Jaronhaven', '83463-8521', 'Hertha83@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Selmer', 'Conn', '4096 Wiegand Field', 'Wolfborough', '19088', 'Christelle39@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Dina', 'Lowe', '204 Effie Causeway', 'North Murray', '15020-4031', 'Arthur7@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Elsie', 'Bayer', '868 Feest Field', 'South Alvena', '35174', 'Otilia.Schultz@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Treva', 'Nicolas', '178 Leffler Coves', 'Lilianeport', '93486', 'Arden_Cartwright42@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Cindy', 'Littel', '01001 Kreiger Loaf', 'North Marisol', '13517-6963', 'Gudrun.McLaughlin@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Frankie', 'Kunze', '5057 Stroman Club', 'West Kiera', '43498-9060', 'Harrison.Barton15@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Robin', 'Schaefer', '46423 Bahringer Hollow', 'East Vivienne', '34676', 'Justice_Jacobi63@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Morris', 'Kiehn', '9346 Haag Summit', 'Kautzerchester', '62696-0240', 'Horacio_Leannon88@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Carissa', 'Satterfield', '98934 Trevor Coves', 'Lednerborough', '26583', 'Marielle_Feil18@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Hobart', 'Klocko', '0716 Nathen Hollow', 'Ursulaside', '38449-2967', 'Valentine10@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Amie', 'Satterfield', '9649 Deborah Crest', 'Dedrickland', '30691', 'Xzavier_Gleichner@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Ilene', 'Graham', '927 Terence Tunnel', 'South Maynard', '33621', 'Stanton83@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Kailyn', 'Ferry', '37796 Josiane Lodge', 'East Michealchester', '30620-6443', 'Eriberto_Heaney45@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Carli', 'Greenholt', '5946 Vito Keys', 'Pfannerstillhaven', '27029', 'Pierre19@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Blanche', 'Kozey', '5071 Destiny Summit', 'North Elouisebury', '08717-6587', 'Linda_Parker13@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Alba', 'Hamill', '132 Daisha Tunnel', 'Nicklausville', '20174', 'Luis38@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Whitney', 'Davis', '8860 Faye Ridges', 'Thompsonberg', '42122', 'Gianni_Smith78@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Laurine', 'Koepp', '866 Frederik Plain', 'New Fatima', '71418', 'Genoveva55@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Kellen', 'Jacobs', '907 Elda Tunnel', 'Port Eino', '49512', 'Rudolph36@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Kole', 'Wilkinson', '094 Reinger Pines', 'New Andreaneville', '14775-3358', 'Ron98@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Aurelio', 'Blanda', '7576 Murphy Harbors', 'Amandaport', '91968', 'Fatima_Boyle87@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Hermann', 'Reynolds', '23482 White Place', 'Lake August', '47065', 'Noelia.Mayert41@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Reagan', 'Hintz', '4099 Effertz Meadow', 'Ortizbury', '34301', 'Vida67@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Dedric', 'Johnston', '8597 Brice Ridges', 'Schillerside', '96392-1453', 'Stanley44@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Asha', 'Brown', '53587 Joyce Plaza', 'New Dahliaburgh', '29822-9597', 'Elenora_Barrows5@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Eugenia', 'Bailey', '044 Terry Keys', 'Lake Flavioberg', '92469', 'Kaci_Balistreri@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Bennie', 'Wiegand', '03644 Susana Court', 'Lake Arielleton', '45944', 'Alexis_Klein36@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Retta', 'Jones', '548 Halvorson Forest', 'Beattyton', '02565', 'Gaston_Carroll@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Zachariah', 'Metz', '894 Mann Village', 'Watsicashire', '99907', 'Robb.Gusikowski@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Leslie', 'Willms', '7863 Satterfield Corners', 'South Maegan', '49071-7701', 'Loren_Swaniawski@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Jewell', 'Towne', '2822 Ian Falls', 'North Jimmy', '86025-4830', 'Georgianna.Von15@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Grayce', 'Olson', '9438 Sunny Wells', 'Fionashire', '73391-8320', 'Deontae74@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Rachel', 'Ebert', '13293 Robbie Field', 'North Unaburgh', '49817-2692', 'Karen.Wunsch10@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Raphaelle', 'Shields', '0620 Jackie Inlet', 'Elimouth', '71729', 'Jack1@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Syble', 'Cummerata', '3069 Roob Locks', 'Trompfurt', '26550-3690', 'Chance.Bahringer96@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Arne', 'Jakubowski', '32241 Summer Forest', 'West Makennafort', '91431-3019', 'Olen.Dibbert@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Amiya', 'Littel', '4009 White Common', 'New Tracyberg', '04096', 'Emory.Ondricka99@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Constance', 'Wilkinson', '52575 Summer Bypass', 'Forrestshire', '34761-8905', 'Shad.Nolan31@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Loraine', 'Quigley', '059 Brown Islands', 'Huelville', '90821', 'Kiana86@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Rosalyn', 'Homenick', '602 Garnet Stream', 'Starktown', '72475-7481', 'Gennaro.Luettgen66@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Marques', 'Tremblay', '8110 Aurelio Port', 'West Lavon', '90244-4977', 'Aurelio70@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Titus', 'Ritchie', '1328 Genoveva Lodge', 'West Ronny', '27212', 'George.Morissette@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Cyrus', 'Stoltenberg', '2898 Klein Alley', 'West Leopoldo', '03937', 'Ivy_Hickle79@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Stewart', 'Heidenreich', '062 Kale Station', 'East Zoie', '61018-0469', 'Chance.Mueller@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Emmie', 'Schuppe', '2189 Predovic Lake', 'Murazikberg', '56161', 'Murray_Wolf@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Devyn', 'Heller', '32992 Horacio Forest', 'Pacochaland', '19963-3407', 'Jackeline10@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Stanley', 'Jacobson', '653 Legros Station', 'Lake Maureenport', '73109-7100', 'Moriah1@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Gracie', 'Nader', '8506 Lakin Shores', 'Vivienborough', '77707-7859', 'Darryl.Hoppe66@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Lew', 'Willms', '0582 O''Kon Track', 'Port Brannonport', '32065', 'Iva.Zulauf45@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Gerda', 'Hickle', '1504 Zita Divide', 'North Reta', '30145', 'Kenyatta_Keebler@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Abbey', 'Krajcik', '270 Henri Ville', 'Parisianburgh', '48127-5871', 'Jairo_Green15@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Mandy', 'Kiehn', '7305 Ernesto Drive', 'McGlynnberg', '43014', 'Humberto72@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Andreanne', 'Nolan', '360 Bailey Branch', 'East Rustytown', '84749-4338', 'Wilmer.Schroeder@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Jo', 'Bosco', '266 Gottlieb Gateway', 'East Thomas', '05348-4908', 'Jude.Gerlach@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Deborah', 'Jakubowski', '3449 Ellsworth Lane', 'New Fausto', '21280-7913', 'Jose.Stracke21@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Daisha', 'Kovacek', '8923 West Manor', 'Hilllborough', '86121', 'Watson.Tillman66@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Barbara', 'Wisoky', '647 Trantow Rest', 'Lake Estebanbury', '50086-7746', 'Jodie11@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Desmond', 'Russel', '7925 Spencer Meadows', 'Sidneyland', '42959-1685', 'Sim_Koch@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Devonte', 'Schowalter', '529 Vance Knoll', 'Alisonshire', '35915-5337', 'Aurelio.Kovacek19@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Raegan', 'Wisoky', '84571 Davis Vista', 'Port Paigeport', '23062', 'Sylvester_Farrell@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Rosetta', 'Hauck', '0009 Gerhold Mountain', 'South Martinton', '12302', 'Muhammad_Maggio@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Iliana', 'Goyette', '91334 Tressa Wall', 'East Haydenview', '97718-0223', 'Kristina.Conn@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Orval', 'Doyle', '281 Spencer Ports', 'Bradleyshire', '83424', 'Valerie_McGlynn14@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Carson', 'Wiza', '5279 Bret Street', 'West Naomiville', '56482', 'Meggie_Glover96@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Jevon', 'Smitham', '1113 Norene Roads', 'Kayliland', '08300-4567', 'Karli.Fritsch36@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Jayne', 'Nikolaus', '271 Karli Island', 'South Chaz', '71750-9284', 'Wilhelmine_Kassulke@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Kim', 'Jones', '428 Marlen Ranch', 'East Wilbert', '70078', 'Vinnie_Gleichner87@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Abdul', 'Hartmann', '59607 Berneice Expressway', 'Lauriemouth', '68204', 'Kiarra93@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Clint', 'Kessler', '3052 Santina Brooks', 'Brantview', '39638', 'Berry10@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Dane', 'Hackett', '1095 Lueilwitz Prairie', 'Kemmerstad', '72641-7795', 'Vicenta64@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Alexane', 'Labadie', '65750 Savanna Causeway', 'Thoraburgh', '43011', 'Kenyatta6@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Elmira', 'Schinner', '97192 Lubowitz Vista', 'Port Clementchester', '80854-3176', 'Keshawn_OConnell@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Elda', 'Rempel', '4526 Toy Inlet', 'Lonnieview', '89930-2342', 'Rhea.Schultz13@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Fabian', 'Kling', '7054 Loy Brook', 'New Elwyn', '93429-4246', 'Spencer_Willms@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Matilda', 'Batz', '647 Dolly Stravenue', 'East Jack', '82339', 'Noah_Cruickshank43@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Maynard', 'Haley', '6912 Cecil Valley', 'Solonville', '31306', 'Abdiel_Rippin84@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Osborne', 'Raynor', '0671 Albert Forks', 'West Aliyafurt', '79773', 'Elise.Dietrich71@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Litzy', 'Jakubowski', '8469 Oma Extensions', 'Boganport', '05783', 'Ross.Reichert29@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Johanna', 'Cronin', '7074 Tillman Locks', 'Port Lloydland', '27406-9061', 'Gordon_Marvin66@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Hermann', 'Hilll', '56132 Dixie River', 'Haleyview', '32190', 'Bart9@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Zechariah', 'Jacobi', '22143 Christian Ranch', 'East Ronny', '55756-4659', 'Avery_Borer10@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Deja', 'Ankunding', '54204 Schmeler Flat', 'Port Jeromy', '37215', 'Selena_Rosenbaum86@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Alene', 'Murazik', '891 Janie Roads', 'East Mateo', '37272-6088', 'Gabe.Halvorson89@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Dax', 'Heathcote', '5641 Wiza Spur', 'Lucienneview', '27224', 'Della69@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Keely', 'Kulas', '941 Isac Bridge', 'New Angie', '24219-8271', 'Myra74@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Eldridge', 'Wiegand', '27091 Shakira Row', 'Osinskihaven', '38638-5612', 'Earlene.Doyle16@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Collin', 'Reinger', '1036 Bill Shoal', 'Furmanburgh', '74071-2723', 'Cassie_Farrell@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Maxime', 'Abernathy', '32330 Ferry Prairie', 'Veumborough', '55143', 'Orion_Swift96@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Daphney', 'Corkery', '944 Keven Forges', 'New Collin', '83618-6041', 'Reinhold.Feil@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Karelle', 'Lang', '198 D''Amore Meadows', 'East Ava', '52383', 'Leonie_Ruecker67@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Toby', 'VonRueden', '67050 Skiles Shore', 'Balistreriside', '88331-1629', 'Alexane_Kreiger19@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Wyman', 'Wolf', '828 Dayana Lakes', 'East Dorian', '43415', 'Cleveland_Gerhold@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Ryan', 'Schimmel', '659 Bella Skyway', 'Lake Helmerside', '54849', 'Eloy_Denesik@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Rosie', 'Weber', '89993 Shyanne Locks', 'McCulloughtown', '91334-8812', 'Arvid92@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Ethyl', 'O''Keefe', '926 Vaughn Rest', 'Lake Maximo', '73656', 'Domenica_Von@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Amani', 'Luettgen', '68111 Christiansen Lakes', 'New Emmittbury', '62176-3094', 'Carleton_Rutherford9@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Preston', 'Nicolas', '03218 Feeney Via', 'East Bufordville', '45101', 'Vidal_Doyle@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Beatrice', 'Shields', '72457 Carmel Parkway', 'Willstad', '72786', 'Emerson50@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Quinten', 'Blick', '6205 Kulas Spring', 'North Bartholome', '62092', 'Annette.Crist5@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Kara', 'Monahan', '43382 Ward Wells', 'North Hermann', '38357', 'Felipa.Flatley@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Arvilla', 'Welch', '784 Quinn Dale', 'Ziemefurt', '51513-0975', 'Libby.Toy2@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Abe', 'Feeney', '833 Peter Overpass', 'Lylaside', '81736', 'Eric.Waters75@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Cheyanne', 'Green', '62003 Grant Orchard', 'Clemmiemouth', '02787', 'Anahi13@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Eduardo', 'McKenzie', '3161 Cremin Street', 'Lebsackview', '66494-5553', 'Elijah.Smith@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Roel', 'Braun', '7733 Beatty Expressway', 'Huelfurt', '09666-5002', 'Pierce.Larkin4@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Cali', 'Gulgowski', '94119 Greenfelder Greens', 'Concepcionburgh', '69096', 'Elenora_Wisoky25@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Monty', 'Goodwin', '683 Aubree Flat', 'Lauryside', '16466-5997', 'Dalton_Gusikowski33@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Myrtice', 'Schmitt', '267 Sawayn Springs', 'Lake River', '44360', 'Lia_Crist22@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Foster', 'Yundt', '715 Funk Springs', 'Lake Jacinto', '31110', 'Justyn_Mayert73@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Sylvan', 'Feil', '01255 Quigley Ridge', 'West Vadafurt', '95888', 'Richard_Romaguera90@gmail.com');
