
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Lorenza','Hammes','32264 McCullough Dale','South Barneyview','66047','Jadyn49@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Savannah','Larson','4184 Grimes Passage','South Kolefort','63769','Alexys_Kertzmann18@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Andy','Keeling','58631 Sabrina Ferry','North Darianachester','64214','Alexander_Hermann88@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Zaria','Schmeler','45114 Alycia Prairie','Lake Marshallbury','01094-7968','Verdie92@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Rene','Bartoletti','5122 Koepp Mall','Ceasarburgh','85985','Gregorio93@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Allen','Daniel','0133 Aaron Plains','Hellerside','56620-7999','Lillie50@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Tate','D''Amore','080 Clara Dam','Floridaside','34804','Michale.Schneider82@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Kaia','Hauck','7285 Melyna Mews','Ardenmouth','96471-7290','Laurie13@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Salvador','Armstrong','077 Rhett Burg','Stephonview','34246-0499','General.Zieme@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Jeffrey','Morissette','2733 Missouri Station','North Keatonside','78331','Ramon_Schamberger33@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Derek','Collier','74807 Andre Keys','Lake Walton','43654','Pamela32@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Mireya','Bayer','3806 Schmidt Center','Botsfordfurt','68417','Maribel48@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Noe','Terry','5014 Kylie Prairie','Bechtelarstad','73703-1197','Addie_Witting@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Bettye','Prohaska','91248 Robel Alley','Hesselchester','25319','Wilhelmine57@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Catharine','Blanda','68867 Stracke Throughway','Port Williamshire','50083-0958','Cordelia_McKenzie31@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Cordia','Welch','0364 Gunner Station','Mattstad','88975','Daren.Dooley@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Jacinto','Funk','4200 Marquardt Vista','New Nyah','56575','Dixie_Crona1@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Malvina','Rau','382 Barton Unions','Kelliborough','60129','Brennan.Crooks26@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Mariane','VonRueden','6250 Nicolas Harbor','Daniellahaven','38059','Erick51@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Giovanny','Becker','867 Bernier Stravenue','Queenhaven','51859','Theo_Dickens44@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Roberto','Nolan','2416 Shanahan Track','Lake Aryannashire','95023-7641','Annette.Carter58@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Delmer','Spencer','3022 Morris Track','West Karinemouth','31253-5914','King_Thiel@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Haven','Kuhlman','4951 Phoebe Gardens','South Velma','17043-6796','Jarod.Yundt49@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Lavada','Torp','759 Ora Summit','Lake Agustin','76089-4476','Edward59@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Addie','O''Reilly','24164 Elinor Brooks','Kiarraberg','67222','Ara92@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Rasheed','Dicki','67840 Hudson Ways','East Kurtisview','09077','Einar_Upton50@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Alanis','Jacobson','60876 Yasmin Isle','Helgaborough','58992-8699','Salvatore.Pollich@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Marcellus','Dach','0932 Luettgen Hills','North Anastaciohaven','35908','Dessie10@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Glenda','Vandervort','72200 Kuvalis Avenue','Wilberchester','12977','Madeline27@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Vincent','Kihn','871 Wolf Garden','West Monroeville','41955','Kirstin_Morissette24@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Maude','Terry','7688 Rogahn Garden','Tonistad','95005-0784','Eunice.Rodriguez21@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Gracie','Bogan','7936 Hickle Isle','South Lucius','94327-6508','Guido_Rohan82@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Ernestine','Buckridge','2117 Rosemarie Valleys','Aliaside','69743-9877','Mireille.McCullough@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Chaz','Fadel','7187 Stiedemann Ports','Adellechester','43097','Keven_Abernathy@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Briana','Wiza','2396 Nicole Causeway','Petraland','35080-4433','Moriah_Thiel51@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Jevon','Tillman','275 Skiles Radial','Salvatoreberg','13453','Valentina_Johnston@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Leslie','Reilly','6451 Alex Knoll','New Lexiehaven','11856','Fae_Wiza@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Yasmin','Ebert','97103 Upton Stravenue','Antonioland','57507','Camille_Wehner19@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Cynthia','Breitenberg','8298 Bashirian Ridge','Port Donavon','81562-9808','Deondre.Kozey54@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Dewayne','Powlowski','45906 Shayne Ramp','South Tristian','48449-9648','Zetta_Strosin@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Dora','Franecki','029 Reinger Spring','Justusfort','07719','Doug.Pfannerstill@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Clint','Herzog','835 Shad Keys','Lake Judsonview','43417-0245','Pattie_Frami@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Afton','Mertz','4055 Mazie Brooks','Port Garth','68149-7275','Gregoria_Berge20@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Lilly','Barrows','602 Rey Via','Erlingbury','17544-3553','Vince_Beahan85@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Justice','Collins','65028 Jakayla Locks','Turnerberg','00173-8124','Annabell_Schiller73@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Erick','Cummerata','88833 Barbara Dale','Kevenstad','89963-0925','Jarrod.Kling@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Nathen','Ryan','80678 Clarabelle Heights','Mayeville','94594','Malinda.Rolfson21@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Pietro','Lang','348 Koch Parkways','Jarrellhaven','11228-0071','Elenora35@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Reginald','Zieme','216 Cornell Street','Raulport','39456','Bartholome10@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Abigale','Willms','1238 Marvin Falls','Lake Emoryburgh','80586','Eldred.Gleason41@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Bulah','Beahan','06827 Ernser Tunnel','West Dino','80536','Aleen.Toy@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Isai','Little','11453 Stiedemann Loop','Wilhelminechester','51296','Presley_Hamill@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Camila','Berge','35316 Lowe Rue','Lake Ayanaton','99713','Turner84@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Kiana','Price','53649 Ulices Villages','Rocioberg','18861-8643','Nathan23@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Dominic','Murray','82263 Trent Key','Kayleighton','12800','Arnoldo_Gleason38@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Armand','Sporer','155 Casimer Wall','Jermeyview','71197','Raquel15@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Julianne','Kuhic','650 Rozella Cape','Rempelport','26625','Alicia.Pfeffer@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Greg','Harris','8878 Tod Roads','Farrellmouth','64473','Everardo38@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Fannie','Lehner','659 Armando Shoals','East Stacey','38492-5487','Carlos_Kessler50@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Curt','Walsh','646 Stanton Spurs','Haleymouth','59700-1692','Ethyl17@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Savannah','Daniel','43368 Rath Rapid','Jonasberg','12500','Rosa.Wintheiser@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Dale','Mueller','76918 Cordie Inlet','South Helene','52553-6367','Robbie74@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Katlynn','Hand','555 Rempel View','Abigayleberg','79014-5150','Aubree_Kiehn10@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Lambert','Rosenbaum','98768 Vickie Skyway','Port Jackeline','44894','Lindsey.Emmerich50@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Marcos','Pfannerstill','204 Karine Burgs','Flatleymouth','37470-2283','Mylene99@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Lila','Renner','34404 Fritsch Estate','Tesstown','05776','Hipolito_Conn70@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Orpha','Pagac','31449 Bartell Dam','Port Otilialand','02123','Dannie5@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Earnestine','Tromp','52097 Konopelski Tunnel','Port Abelardoberg','30286-5175','Rhiannon70@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Makenna','Kautzer','74514 Walter Mountain','Venahaven','38412-4502','Madalyn_Walsh96@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Isabell','Jakubowski','858 Abigail Springs','Cruickshankfurt','19702-9069','Alverta_Green@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Felipe','Gislason','512 Glover Burg','East Genovevahaven','87634','William.Pollich91@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Nathan','Block','93501 Jolie Ports','Port Jimmie','79558','Noemy_Gottlieb@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Tad','Jerde','30299 Madyson Centers','West Vilmaton','22350','Harley3@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Jerrod','Russel','38091 Ottis Estates','South Melba','35780','Arno_Johnston52@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Antonio','Bahringer','07877 Ezra Run','Jonathanton','09958','Francesco_Veum@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Meredith','Stamm','7648 Hintz Ridges','Mrazport','25629','Freddie.Prosacco81@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Destany','Eichmann','79308 Parker Place','Cartwrightville','58534-7508','Denis.Orn57@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Aurelio','Kulas','595 Dicki Corners','Kshlerinmouth','21754-0385','Dora30@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Royce','Pfeffer','963 Marc Wall','Port Sally','23101','Maya.Prohaska85@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Precious','Harber','906 Kuhic Junction','Francishaven','54737-7479','Kole2@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Emily','Turcotte','9107 Wiegand Branch','South Juwan','35778-2245','Emilia.Abbott@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Vena','Wolff','129 Elise Way','East Adrienneport','48861-4500','Kendrick0@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Jessyca','Cremin','78685 Verdie Lane','Port Alexander','32874-0181','Clarissa62@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Ernesto','Wiza','401 O''Kon Ridges','McClurechester','81690-1129','Zachariah7@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Estell','Rowe','656 Effertz Causeway','West Avery','00172','Darren56@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Darien','Hessel','42372 Jamaal Junctions','Pfefferborough','37874','Joany29@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Ike','Goyette','61162 Volkman Neck','Schuylerfort','15334','Ellis.Monahan@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Carole','Beer','11969 Arden Square','Danikamouth','17832-9127','Brooke.Breitenberg54@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Santiago','Stamm','724 Hammes Cliffs','West Lavon','67863','Phoebe20@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Geovany','Nolan','4025 Satterfield Common','East Gregghaven','65746-1437','Miracle_Bayer@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Dwight','Kuphal','60225 Tiffany Dale','East Paigehaven','93797-5039','Marlen8@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Troy','Renner','51993 Margaretta Trafficwa','West Robbieside','22373','Chet.Boehm@yahoo.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Mossie','Shanahan','839 Price Spring','South Jamilside','78236-4266','Jeromy_Langosh6@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Mabel','Parisian','22693 Bosco Course','West Rosario','15361','Melissa.VonRueden70@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Reid','Orn','2358 Feil Plaza','Trevaville','63003-1301','Milton.Bayer@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('German','Herman','025 Gerry Islands','Waelchiberg','63480','Jules.Sipes@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Neha','Mraz','566 Ruben Spur','West Robbieborough','43067','Jabari.Conn60@hotmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Daisy','Kassulke','32409 Schumm Lake','Alexanderbury','39458','Janie_Adams@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Margaret','Mayert','85058 Medhurst Lakes','West Tyson','02805','Imogene.Barton@gmail.com');
INSERT INTO customer (firstName, lastName, address, city, zipcode, email) values ('Ian','Marks','74285 Eulah Union','Earlinemouth','53200-2585','Marty62@gmail.com');

select * from customer